apiVersion: v1
kind: Pod
metadata:
  name: study-app
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: 074177506936.dkr.ecr.us-west-2.amazonaws.com/study-app:latest
      ports: 
        - containerPort: 80
