apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort #LoadBalancer NodePort ClusterIP
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111 #30000-32767
    protocol: TCP
  selector:
    app: web